program: sweep.py
method: bayes
name: "cub200_auroc_sweep"
metric:
  name: test_metric/auroc
  goal: maximize
parameters:
  hessian_memory_factor:
    min: 0.99
    max: 0.999
  type_of_triplets:
    value: "hard"
  type_of_triplets_hessian:
    values: ["hard", "semihard", "all"]
  max_pairs:
    value: 30
  config: 
    value: '../configs/cub200/laplace_online_arccos_pos.yaml'