program: sweep.py
method: bayes
name: "lfw_auroc_sweep"
metric:
  name: test_map/map@5
  goal: maximize
parameters:
  hessian_memory_factor:
    min: 0.999
    max: 0.9999999
  margin:
    min: 0.1
    max: 1.0
  type_of_triplets:
    values: ["hard", "semihard", "all"]
  type_of_triplets_hessian:
    values: ["hard", "semihard", "all"]
  max_pairs:
    values: [5, 30]
  config: 
    value: '../configs/lfw_fred/laplace_online_arccos_fix.yaml'