


# model specific
model : "deterministic"
resume : ""
arch : "resnet50"
latent_dim : 3
pool : "gem"

# logging
log_dir : "../results"

# training
train : True
epochs : 20
lr : 0.0001
loss : "contrastive"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/data/MSLS"
dataset : "msls"
batch_size : 12
image_size : 224
split_query_database : False

train_cities : "zurich"
val_cities : "zurich"
test_cities : "zurich"
posDistThr : 10
negDistThr : 25
