


# model specific
model : "deterministic"
resume : ""
arch : "resnet50"
pool : "gem"
whitening : True
pretrained : True
latent_dim : 512

# logging
log_dir : "../results"
check_val_every_n_epoch : 1

# training
train : True
epochs : 10
lr : 3.0e-6
loss : "contrastive"
margin : 1
distance : "euclidean"
type_of_triplets : "semihard" # easy, semihard, hard, all

# data specific
data_dir : "/home/warburg/data/"
dataset : "msls"
batch_size : 64
split_query_database : False
negDistThr : 25
posDistThr : 10
