


# model specific
model : "laplace_online"
arch : "resnet50"
pool : "gem"
whitening : True
pretrained : True
latent_dim : 512

# hessian
hessian_memory_factor : 0.99999 # 1 - 1.0e-7
init_hessian : 1.0e+6
scale_hessian : 1.0e+6
loss_approx : "fix"
max_pairs : 10
type_of_triplets : "all" # easy, semihard, hard, all
type_of_triplets_hessian : "semihard" # easy, semihard, hard, all

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 20
lr : 3.0e-7
loss : "arccos"
margin : 0.1
distance : "euclidean"
weight_decay : 1.0e-6

# data specific
data_dir : "/home/warburg/data/"
dataset : "msls"
batch_size : 64
split_query_database : False
negDistThr : 25
posDistThr : 10

