


# model specific
model : "deterministic"
resume : ""
arch : "linear"
latent_dim : 3

# logging
log_dir : "../results"

# training
train : True
epochs : 20
lr : 0.001
loss : "contrastive"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/data/"
dataset : "mnist"
batch_size : 256
split_query_database : False
