


# model specific
model : "pfe"
resume : ""
arch : "linear"
latent_dim : 3
resume : "../lightning_logs/mnist/deterministic"

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 20
lr : 0.001
loss : "contrastive"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/data/"
dataset : "mnist"
batch_size : 256
split_query_database : False
