


# model specific
model : "laplace_posthoc"
arch : "resnet50"
pool : "gem"
whitening : True
resume : "lightning_logs/lfw/deterministic"
latent_dim : 512

# hessian
loss_approx : "pos"
max_pairs : 30
type_of_triplets : "semihard" # easy, semihard, hard, all

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 200
lr : 3.0e-7
loss : "contrastive"
margin : 1
distance : "euclidean"

# data specific
data_dir : null
dataset : "lfw"
batch_size : 64
split_query_database : False

