


# model specific
model : "laplace_online"
arch : "resnet50"
pool : "gem"
whitening : True
pretrained : True
latent_dim : 512

# hessian
hessian_memory_factor : 0.995
loss_approx : "fix"
max_pairs : 30
type_of_triplets : "semihard" # easy, semihard, hard, all
type_of_triplets_hessian : "semihard" # easy, semihard, hard, all

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 200
lr : 3.0e-7
loss : "arccos"
margin : 1
distance : "euclidean"
# train_n_samples : 10

# data specific
data_dir : "/scratch/toskov/data/"
dataset : "lfw"
batch_size : 64
split_query_database : False

