


# model specific
model : "laplace_online"
resume : ""
arch : "resnet50"
pool : "gem"
whitening : True
pretrained : True
latent_dim : 512
type_of_triplets : "semihard"

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 200
lr : 3.0e-7
loss : "contrastive"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/work3/s174433/datasets/"
dataset : "lfw"
batch_size : 64
split_query_database : False
