


# model specific
model : "mc_dropout"
resume : ""
arch : "resnet50"
pool : "gem"
whitening : True
latent_dim : 512
dropout_rate : 0.05

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 200
lr : 3.0e-7
loss : "contrastive"
margin : 1
distance : "euclidean"
type_of_triplets : "semihard"

# data specific
data_dir : "/work3/s174433/datasets/"
dataset : "lfw"
batch_size : 64
split_query_database : False
