


# model specific
model : "pfe"
resume : ""
arch : "resnet50"
pool : "gem"
whitening : True
resume : "../lightning_logs/lfw/deterministic"
latent_dim : 512

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 10
lr : 3.0e-7
loss : "contrastive"
margin : 1
distance : "euclidean"
type_of_triplets : "semihard"

# data specific
data_dir : "/scratch/toskov/data/"
dataset : "lfw"
batch_size : 64
split_query_database : False
