


# model specific
model : "deep_ensemble"
resume : ""
arch : "resnet50"
pool : "gem"
whitening : True
resume : "../lightning_logs/cub200/deterministic"
latent_dim : 512
seeds : [1,2,3,4,5]

# logging
check_val_every_n_epoch: 1

# training
train : False
epochs : 0
lr : 0.001
loss : "contrastive"
margin : 1
distance : "euclidean"
type_of_triplets : "semihard"

# data specific
data_dir : "/scratch/toskov/data/
dataset : "cub200"
batch_size : 64
split_query_database : False
