


# model specific
model : "deterministic"
resume : ""
arch : "resnet50"
pool : "gem"
whitening : True
pretrained : True
latent_dim : 512

# logging
log_dir : "../results"
check_val_every_n_epoch : 1

# training
train : True
epochs : 10
lr : 3.0e-7
loss : "contrastive"
margin : 1
distance : "euclidean"

# data specific
data_dir : "/data/"
dataset : "cub200"
batch_size : 64
split_query_database : False
