


# model specific
model : "hib"
resume : ""
arch : "linear"
latent_dim : 3
kl_weight : 1.0e-4

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 20
lr : 0.00001
loss : "contrastive"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/scratch/toskov/data/"
dataset : "cub200"
batch_size : 64
split_query_database : False