


# model specific
model : "hib"
resume : ""
arch : "resnet50"
pool : "gem"
whitening : True
pretrained : True
latent_dim : 512
type_of_triplets : "semihard"
kl_weight : 1.0e-4

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 10
lr : 0.001
loss : "contrastive"
margin : 1
distance : "euclidean"

# data specific
data_dir : "/scratch/toskov/data/"
dataset : "cub200"
batch_size : 64
split_query_database : False