


# model specific
model : "laplace_online"
arch : "resnet50"
pool : "gem"
whitening : True
pretrained : True
latent_dim : 512

# hessian
hessian_memory_factor : 0.9997
init_hessian : 1.0e+6
loss_approx : "fix"
max_pairs : 30
type_of_triplets : "semihard" # easy, semihard, hard, all
type_of_triplets_hessian : "all" # easy, semihard, hard, all

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 20
lr : 3.0e-7
loss : "arccos"
margin : 1
distance : "euclidean"

# data specific
data_dir : "/scratch/toskov/data/
dataset : "cub200"
batch_size : 64
split_query_database : False

