


# model specific
model : "laplace_posthoc"
resume : "../lightning_logs/fashionmnist/deterministic"
arch : "linear"
latent_dim : 3

# hessian
loss_approx : "full"
max_pairs : 5000
type_of_triplets : "all" # easy, semihard, hard, all

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 20
lr : 0.001
loss : "arccos"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/scratch/toskov/data/
dataset : "fashionmnist"
batch_size : 64
split_query_database : False
