


# model specific
model : "deep_ensemble"
resume : "../lightning_logs/cifar10/deterministic"
arch : "linear"
latent_dim : 16
seeds : [1,2,3,4,5]

# logging
check_val_every_n_epoch: 1

# training
train : False
epochs : 0
lr : 0.001
loss : "contrastive"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/scratch/toskov/data/
dataset : "cifar10"
batch_size : 256
split_quesry_database : False
