


# model specific
model : "laplace_online"
arch : "linear"
latent_dim : 16

# hessian
hessian_memory_factor : 0.999
loss_approx : "fix"
max_pairs : 5000
type_of_triplets : "all" # easy, semihard, hard, all
type_of_triplets_hessian : "hard" # easy, semihard, hard, all

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 40
lr : 0.00001
loss : "arccos"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/home/warburg/data/"
dataset : "cifar10"
batch_size : 256
split_query_database : False

