


# model specific
model : "mc_dropout"
resume : ""
arch : "linear"
latent_dim : 3
dropout_rate : 0.05

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 20
lr : 0.00001
loss : "contrastive"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/scratch/toskov/data/"
dataset : "cifar10"
batch_size : 256
split_query_database : False
