


# model specific
model : "laplace_posthoc"
resume : "../lightning_logs/lfw/deterministic"
arch : "resnet50"
pool : "gem"
whitening : True
pretrained : True
latent_dim : 512

# logging
check_val_every_n_epoch: 1

# training
train : True
epochs : 20
lr : 0.001
loss : "contrastive"
margin : 0.7
distance : "euclidean"

# data specific
data_dir : "/work3/s174433/datasets/"
dataset : "lfw"
batch_size : 256
split_query_database : False
